server:
  port: 8083
spring:
  application:
    name: oauthclientservice
  config:
    import: optional:file:.env[.properties]
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: reader
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8081/realms/pluralsight/protocol/openid-connect/token
get-bugs-uri: http://localhost:9090/bugs